baseURL = "http://example.org/"
defaultContentLanguage = "fr"
languageCode = "fr-fr"
theme = "uno"
title = "Simon Meriadec"
[languages.en]
languageName = "English"
weight = 2
[[languages.en.menu.main]]
identifier = "quote"
name = "Quote"
url = "/quote/"
weight = 1
[[languages.en.menu.main]]
identifier = "interets"
name = "Interests"
url = "/interests/"
weight = 2
[[languages.en.menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
weight = 3
[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
[languages.en.params]
description = "Freelance french translator"
home = "Home"
[languages.es]
languageName = "Español"
weight = 3
[[languages.es.menu.main]]
identifier = "quote"
name = "Presupuesto"
url = "/quote/"
weight = 1
[[languages.es.menu.main]]
identifier = "interets"
name = "Aficción"
url = "/interests/"
weight = 2
[[languages.es.menu.main]]
identifier = "about"
name = "Conocerme"
url = "/about/"
weight = 3
[[languages.es.menu.main]]
identifier = "contact"
name = "Contacto"
url = "/contact/"
weight = 4
[languages.es.params]
description = "Traductor francés autonomo"
home = "Inicio"
[languages.fr]
languageName = "Français"
weight = 1
[[languages.fr.menu.main]]
identifier = "quote"
name = "Devis"
url = "/quote/"
weight = 1
[[languages.fr.menu.main]]
identifier = "interests"
name = "Intérêts"
url = "/interests/"
weight = 2
[[languages.fr.menu.main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 3
[[languages.fr.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
[params]
author = "Simon Meriadec"
description = "Traducteur Freelance"
home = "Accueil"
logo = "Simon Meriadec"
logoSmall = "SM"
[privacy.youtube]
disable = false
privacyEnhanced = true
[taxonomies]
category = ""
tag = ""
