baseURL = "http://example.org/"
languageCode = "fr-fr"
title = "Simon Meriadec"
theme = "uno"

defaultContentLanguage = "fr"

[params]
  logo = "Simon Meriadec"
  logoSmall = "SM"
  description = "Traducteur bg"
  home = "Accueil"
  author = "Simon Meriadec"

[taxonomies]
  tag = "tags"
  category = ""

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    [[languages.fr.menu.main]]
      identifier = "quote"
      name = "Devis"
      url = "/quote/"
      weight = 1
    [[languages.fr.menu.main]]
      identifier = "interests"
      name = "Intérêts"
      url = "/interests/"
      weight = 2
    [[languages.fr.menu.main]]
      identifier = "about"
      name = "À propos"
      url = "/about/"
      weight = 3
    [[languages.fr.menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 4
  [languages.en]
    languageName = "English"
    weight = 2
    [languages.en.params]
      description = "Really good translator"
      home = "Home"
    [[languages.en.menu.main]]
      identifier = "quote"
      name = "Quote"
      url = "/quote/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "interets"
      name = "Interests"
      url = "/interests/"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About me"
      url = "/about/"
      weight = 3
    [[languages.en.menu.main]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 4
  [languages.es]
    languageName = "Español"
    weight = 3
    [languages.es.params]
      description = "Un traductor muy bueno"
      home = "Inicio"
    [[languages.es.menu.main]]
      identifier = "quote"
      name = "Presupuesto"
      url = "/quote/"
      weight = 1
    [[languages.es.menu.main]]
      identifier = "interets"
      name = "Aficción"
      url = "/interests/"
      weight = 2
    [[languages.es.menu.main]]
      identifier = "about"
      name = "Conocerme"
      url = "/about/"
      weight = 3
    [[languages.es.menu.main]]
      identifier = "contact"
      name = "Contacto"
      url = "/contact/"
      weight = 4

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
